import 'dart:convert';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:image_picker/image_picker.dart';
import '../models/junk_component.dart';
import 'firebase_service.dart';

/// Senior Flutter & AI Engineer implementation of ComponentAnalysisService
class ComponentAnalysisService {
  final GenerativeModel _model;
  final FirebaseService _firebaseService = FirebaseService();

  ComponentAnalysisService()
      : _model = GenerativeModel(
          model: 'gemini-1.5-flash',
          apiKey: dotenv.get('GEMINI_API_KEY'),
          generationConfig: GenerationConfig(
            responseMimeType: 'application/json',
          ),
        );

  /// Analyze junk component using Gemini-1.5-Flash
  Future<JunkComponent> analyzeJunk(XFile image, String userDamageDesc) async {
    try {
      final imageBytes = await image.readAsBytes();

      // AI Instructions (The "Brain")
      final prompt = """
Analyze this image. Identify the component. Search for its specs. Combine this with the user's report: [$userDamageDesc].
Return a JSON object containing:
'aiLabel': Specific technical name of the component.
'description': A professional technical summary.
'dismantleTime': Estimated time.
'suggestedProjects': A list of 3 unique mini-projects.
'integrationTips': How to use this with parts currently in a typical 'Home Page' collection.
""";

      final response = await _model.generateContent([
        Content.multi([
          TextPart(prompt),
          DataPart('image/jpeg', imageBytes),
        ]),
      ]);

      final text = response.text;
      if (text == null) {
        throw Exception('AI Analysis returned empty response');
      }

      final Map<String, dynamic> data = safeParseJson(text);

      // Validation: Implement a "Mismatch Check"
      bool needsManualVerification = false;
      final String descLower = userDamageDesc.toLowerCase();
      final String aiDescription = (data['origin'] ?? '').toString().toLowerCase();
      
      // If user says "New" but AI detects "Cracked Circuit"
      if (descLower.contains('new') && aiDescription.contains('cracked circuit')) {
        needsManualVerification = true;
      }
      // General damage mismatch check
      if (descLower.contains('new') && (aiDescription.contains('damaged') || aiDescription.contains('broken'))) {
        needsManualVerification = true;
      }

      final junk = JunkComponent(
        id: '', // Generated by Firestore
        aiLabel: data['aiLabel'] ?? 'Unknown Component',
        imageUrl: '', // Image URL should be set after uploading to Storage if needed
        userDamageDesc: userDamageDesc,
        origin: data['origin'] ?? '',
        aiSuggestedProject: data['aiSuggestedProject'] ?? 'AI Pending',
        dismantleTime: data['dismantleTime'] ?? 'Unknown',
        isVerified: false,
        adminVerified: false,
        mismatch: needsManualVerification,
        mismatchExplanation: data['explanation'] ?? '',
        timestamp: DateTime.now(),
      );

      // Persistence: Automatically trigger a saveToFirestore call (Mumbai Region project)
      final docId = await _firebaseService.saveJunkComponent(junk);
      
      return JunkComponent.fromJson(junk.toJson(), docId);
    } catch (e) {
      throw Exception('Component analysis failed: $e');
    }
    }

  Map<String, dynamic> safeParseJson(String text) {
    try {
      final jsonRegex = RegExp(r'\{[^{}]*?(?:\{[^{}]*?\}[^{}]*?)*\}');
      final match = jsonRegex.firstMatch(text);
      final cleaned = match?.group(0) ?? '{}';
      Map<String, dynamic> parsed = jsonDecode(cleaned) as Map<String, dynamic>;
      return parsed;
    } catch (e) {
      print('Component Analysis JSON Fallback: $e');
      return {
        'aiLabel': 'Unknown',
        'origin': '',
        'aiSuggestedProject': 'Fallback',
        'dismantleTime': 'Unknown',
        'explanation': '',
      };
    }
  }
}
